#include "stm32f0xx.h"

void tim_irq_init(void) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = 48000 - 1;
	TIM2->ARR = 1000 - 1;
	TIM2->DIER |= TIM_DIER_UIE;
	NVIC_EnableIRQ(TIM2_IRQn);
	TIM2->CR1 |= TIM_CR1_CEN;
}

void tim_pwm_init(void) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER0_Msk;
	GPIOA->MODER |= GPIO_MODE_AF_PP << GPIO_MODER_MODER0_Pos;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFRL0_Msk;
	GPIOA->AFR[0] |= GPIO_AF2_TIM2 << GPIO_AFRL_AFRL0_Pos;

	TIM2->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2;
	TIM2->CCER |= TIM_CCER_CC1E;
	TIM2->PSC = 48000 - 1;
	TIM2->ARR = 1000 - 1;
	TIM2->CCR1 = 200 - 1;
	TIM2->CR1 |= TIM_CR1_CEN;
}

void tim_encoder_init(void) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER0_Msk;
	GPIOA->MODER &= ~GPIO_MODER_MODER1_Msk;
	GPIOA->MODER |= GPIO_MODE_AF_PP << GPIO_MODER_MODER0_Pos;
	GPIOA->MODER |= GPIO_MODE_AF_PP << GPIO_MODER_MODER1_Pos;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFRL0_Msk;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFRL1_Msk;
	GPIOA->AFR[0] |= GPIO_AF2_TIM2 << GPIO_AFRL_AFRL0_Pos;
	GPIOA->AFR[0] |= GPIO_AF2_TIM2 << GPIO_AFRL_AFRL1_Pos;

	TIM2->CCMR1 |= TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0;
	TIM2->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;
	TIM2->SMCR |= TIM_SMCR_SMS_0 | TIM_SMCR_SMS_1; // encoder mode on 2 phases
	TIM2->ARR = 0xFFFF;
	TIM2->CR1 |= TIM_CR1_CEN;
}

void TIM2_IRQHandler(void) {
	if( TIM2->SR & TIM_SR_UIF ) {
		TIM2->SR &= ~TIM_SR_UIF;
		GPIOB->ODR ^= 1 << 1;
	}
}
